name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: onboarding-host-77ae2923a5f448
  GAR_LOCATION: us-central1 
  GKE_CLUSTER: cluster-1 
  GKE_ZONE: us-central1
  REPOSITORY: demo
  IMAGE: static-site

jobs:
  build-push-gcr:
    name: Build and push to gcr
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    #Authenticate with GCP
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
    #Configure Docker
    - name: Docker configuration  
      run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin us-central1-docker.pkg.dev
    
    #GKE config
    - name: Setup GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE}}
   
    # Build the Docker Image
    - name: Build
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
    #Install Skaffold
    - name: Install Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        sudo install skaffold /usr/local/bin/
    
    # Deploy through skaffold
    - name: Deploy to GKE with skaffold
      run: skaffold run

    


   
